package ua.com.smartjava;

import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.SparkSession;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Spark {
    public static void main(String[] args) {
        //Old-way spark start
        SparkConf sprakConfig = new SparkConf().setAppName("SparkJoins").setMaster("local[*]");

        JavaSparkContext sc = new JavaSparkContext(sprakConfig);

        JavaRDD<String> fileStrings = sc.textFile("./1.log");
        JavaRDD<Integer> map = fileStrings
                .filter(str -> str.contains("a"))
                .map(String::length);
        int total = map.reduce((a, b) -> a + b);
        System.out.println("total: " + total);
        sc.close();

        // New-way spark start since 2.0 version
        String logFile = "./1.log"; // Should be some file on your system
        SparkSession spark = SparkSession.builder().appName("Simple Application")
                .master("local[*]")
                .getOrCreate();
        Dataset<String> logData = spark.read().textFile(logFile).cache();

        long count = logData.distinct().filter(s -> s.length() > 2).count();
        System.out.println(count);

        long numAs = logData.filter(s -> s.contains("a")).count();
        long numBs = logData.filter(s -> s.contains("b")).count();

        System.out.println("Lines with a: " + numAs + ", lines with b: " + numBs);

        spark.stop();
    }


}
